development:
  cloud_name: 'dqkqb0ezf'
  api_key: '248989752439865'
  api_secret: 'G6RfkdA98nhYb7BhKeQclwu00TA'

production:
  cloud_name: <%= ENV['dqkqb0ezf'] %>
  api_key: <%= ENV['248989752439865'] %>
  api_secret: <%= ENV['G6RfkdA98nhYb7BhKeQclwu00TA'] %>
  secure: true
  cdn_domain: true